- src/components/Layout.jsx
- src/components/QuickLinks.jsx
- src/pages/dapp-development/build-your-first-dapp/index.md
- src/pages/dapp-development/framework-best-practices/index.md
- src/pages/defi/defi-tokens/index.md
- src/pages/nft/build-an-nft-marketplace/index.md
- src/pages/nft/create-an-nft/index.md
- src/pages/tezos-basics/deploy-your-first-smart-contract/index.md
- src/pages/tezos-basics/get-started-with-octez/index.md
- src/pages/tezos-basics/smart-contract-languages/index.md
- src/pages/tezos-basics/test-networks/index.md
- src/pages/tezos-basics/tezos-protocol-and-shell/index.md
fixed broken link in smart contracts section and other edits
> Solomon@docs staging review

- src/pages/tezos-basics/deploy-your-first-smart-contract/index_ligo.md
- src/pages/tezos-blockchain-overview/what-is-tezos.md
The Ligo tutorial is structured to mirror the SmartPy tutorial.
The "what is Tezos" article may need to be adjusted if the goal was to write something about Tezos as a cryptocurrency.
> Article about Tezos + Ligo tutorial

- src/pages/tezos-blockchain-overview/skeleton_template.md
This just has the skeleton template doc. It's within "Tezos Blockchain Overview" section and will only be visible in the menu if included in the Layout.jsx file. 
Otherwise you can reach it directly (but will be missing the title and breadcrumb.) http://localhost:3000/developers/docs/tezos-blockchain-overview/skeleton_template/
> Solomon@template skeleton doc

- src/components/Layout.jsx
- src/pages/defi/ctez/index.md
- src/pages/defi/stablecoins/index.md
- src/pages/defi/synthetics/index.md
- src/pages/defi/wrapped-assets/index.md
- src/pages/index.md
- src/pages/resources/index.md
- src/pages/tooling/index.md
- src/pages/tutorials/index.md
Defi sections on ctez, synthetics, stablecoins
> Solomon@defi sections cleanup

- src/components/Layout.jsx
- src/pages/tezos-basics/get-started-with-octez/best-practices/index.md
- src/pages/tezos-basics/get-started-with-octez/monitor-a-node/index.md
- src/pages/tezos-basics/get-started-with-octez/upgrade/index.md
Adding additional octez sections on upgrade, monitor, and best practices
> Solomon@node upgrade monitoring

- src/pages/resources/tezos-blockchain-overview/whitepaper.md
- src/pages/tezos-blockchain-overview/whitepaper.md
- src/pages/tooling/tezos-blockchain-overview/whitepaper.md
- src/pages/tutorials/tezos-blockchain-overview/whitepaper.md
> whitepaper latex fixes

- src/pages/nft/create-an-nft/nft-pinata.md
- src/pages/resources/tezos-blockchain-overview/governance/functional-programming.md
- src/pages/tezos-basics/get-started-with-octez/installation-and-setup.md
- src/pages/tezos-basics/tezos-protocol-and-shell/index.md
- src/pages/tezos-blockchain-overview/governance/functional-programming.md
- src/pages/tooling/tezos-blockchain-overview/governance/functional-programming.md
- src/pages/tutorials/tezos-blockchain-overview/governance/functional-programming.md
A review of a number of pages-- This can be merged
> various edits across functional-programming, others

- src/components/Layout.jsx
- src/pages/smart-contracts/avoiding-flaws/index.md
- src/pages/tezos-blockchain-overview/governance/governance-overview.md
- src/pages/tezos-blockchain-overview/governance/improvement-process-tzip.md
- src/pages/tezos-blockchain-overview/governance/intro.md
- src/pages/tezos-blockchain-overview/positionpaper.md
- src/pages/tezos-blockchain-overview/whitepaper.md
* reviewed all of avoiding-flaws.md 
* added it back into the navigation tree
* removed TOCs from whitepaper and position paper
* removed double heading from governance overview page
> Sasha@avoiding flaws

- markdoc/tags.js
- package-lock.json
- package.json
- src/components/CalendlyEmbed.jsx
- src/components/Layout.jsx
- src/components/Navigation.jsx
- src/pages/office-hours/index.md
- src/pages/tutorials/index.md
* add office hours link with calendly embed
* add tutorials placeholder page with lg-links
* make top level pages expandable to clean up navigation tree
* split "DeFi, NFTs and Gaming" into "DeFi", "NFTs" and "Gaming"
> navigation additions

- src/components/Layout.jsx
- src/pages/smart-contracts/token-standards/index.md
* remove wrapped assets, stablecoins from defi section
* move token standards to smart contracts
> remove pages

- package-lock.json
- src/components/LgLinks.jsx
* fix smart rollup link on homepage
> fix lglink behaviour when tagged

- src/pages/tezos-basics/tezos-protocol-and-shell/index.md
> changed nomadic labs documentation to Tezos' technical documentation

- src/pages/tutorials/deploy-your-first-smart-contract/jsligo/index.md
The command should be:
```
ligo run dry-run increment.jsligo -m Counter -e increment "32" "10"
```
> This command is different for jsligo

- src/components/Layout.jsx
- src/pages/tutorials/build-your-first-app/adding-removing-liquidity.md
- src/pages/tutorials/build-your-first-app/index.md
- src/pages/tutorials/build-your-first-app/setting-up-app.md
- src/pages/tutorials/build-your-first-app/swapping-tokens.md
- src/pages/tutorials/build-your-first-app/wallets-tokens.md
Updates to the web app tutorial that I did while going through it for the first time.
Things to review in particular:
- My statements about how dApps and this dApp in particular behave
- Info about the LB contract and how we call it
- Info about what's actually happening when the app calls the contract
See the preview for a running version: https://docs-staging-git-feat-update-web-app-tutorial-trili-tech.vercel.app/tutorials/build-your-first-app/
In the long term, I'd like to have a dApp that will work on testnet; this does not because the LB contract on ghostnet has no tzBTC. I'd also like to have a less-complicated contract that is more coding and less "copy these files from the working application."
Before deploying, we must set the https://github.com/trilitech/tutorial-applications/ …
> Update web app tutorial

- src/pages/index.js
* Revert "Hide Calendly for now (#144)"
This reverts commit 32ccf62d2ac7cfa3ea3a896ea80a1182c7636dd5.
* TriliTech Developer Success team
> Merge calendly update to main

- src/pages/index.js
Provide an anchor so we can link to https://docs.tezos.com/#office-hours
> Anchor for office hours

- docs/architecture/tokens/FA1.2.md
- docs/architecture/tokens/FA2.md
While working on something else, I tweaks the descriptions of the permissions in the FA1.2 and FA2 topics.
> Clarify token transfers

- docs/dApps/sending-transactions.md
- docs/smart-contracts/logic/operations.md
- sidebars.js
Basic task-based information on calling contracts from dApps, covering Beacon, Taquito, and a little about octez.
Preview: https://docs-staging-git-calling-contracts-trili-tech.vercel.app/docs/dApps/sending-transactions
> Topic on calling contracts from dApps

- docs/dApps/taquito.md
- docs/tutorials/build-your-first-app/sending-transactions.md
- docs/tutorials/build-your-first-app/setting-up-app.md
- docs/tutorials/build-your-first-app/wallets-tokens.md
- docs/tutorials/create-an-nft/nft-web-app/defining-functions.md
- docs/tutorials/create-an-nft/nft-web-app/setting-up-app.md
Fix for https://github.com/trilitech/tezos-developer-docs/issues/166 and https://github.com/trilitech/tezos-developer-docs/issues/165.
> Correct how network is specified in Taquito

- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
https://github.com/trilitech/tezos-developer-docs/pull/168 didn't work because of a permissions error. Try `--delete` to remove old files.
> Use --delete to remove old files

- package-lock.json
- package.json
- src/components/ChatBob.jsx
- src/components/Footer/index.jsx
Restore the chatbob chat program.
> Restore chatbob

- sidebars.js
Not sure why, but this topic was causing the build to crash. This PR restores it.
> Restore serialization topic

- docusaurus.config.js
- package-lock.json
- package.json
Enable mermaid diagrams as described in https://docusaurus.io/docs/markdown-features/diagrams as needed for https://github.com/trilitech/tezos-developer-docs/pull/197.
> Enable mermaid diagrams

- package-lock.json
- package.json
> Docusaurus v3.0.1

- docs/smart-contracts/data-types/complex-data-types.md
> Correct link to octez docs on right combs

- docusaurus.config.js
Need to get CSP headers working so we can use google analytics.
> Set up CSP headers

- docs/architecture/governance/amendment-history.md
- docs/dApps/taquito.md
- docs/developing/testnets.md
- docs/overview/tezos-different.md
- docs/smart-contracts/creating.md
- docs/smart-contracts/deploying.md
- docs/smart-contracts/languages/ligo.md
- docs/tutorials.mdx
- docs/tutorials/create-an-nft/fa12/index.md
- docs/tutorials/dapp.md
- docs/tutorials/dapp/part-1.md
- docs/tutorials/dapp/part-2.md
- docs/tutorials/dapp/part-3.md
- Do not capitalize "smart contract"
- Capitalize LIGO, CameLIGO, and JsLIGO
- Don't capitalize "tez"
> Capitalization fixes

- docs/architecture/accounts.md
Add smart rollups to the list of account types
> Add Smart Rollup as a type of account

- package.json
These scripts came in by accident via https://github.com/trilitech/tezos-developer-docs/pull/225.
> Remove unused scripts

- docs/dApps.md
- docs/dApps.mdx
- sidebars.js
Preview: https://docs-staging-git-dapp-landing-page-trili-tech.vercel.app/dApps
> Simple landing page for dApps section

- docs/architecture/smart-rollups.mdx
> Put the correct Smart Rollup diagram in the topic

- docs/tutorials/build-files-archive-with-dal/get-slot-info.mdx
- docs/tutorials/build-files-archive-with-dal/publishing-on-the-dal.mdx
Make it explicit that we have to select weeklynet in Explorus.
> Select weeklynet in explorus

- docs/architecture/tokens.md
- docs/dApps.mdx
- docs/dApps/sending-transactions.md
- docs/dApps/wallets.md
- docs/overview/quickstart.md
- docs/tutorials.mdx
- docs/tutorials/build-an-nft-marketplace/part-1.md
- docs/tutorials/build-files-archive-with-dal.mdx
- docs/tutorials/build-files-archive-with-dal/get-dal-params.mdx
- docs/tutorials/build-your-first-app.md
- docs/tutorials/create-an-nft.md
- docs/tutorials/create-an-nft/nft-tznft.md
- docs/tutorials/smart-contract/archetype.md
- docs/tutorials/smart-contract/cameligo.mdx
- docs/tutorials/smart-contract/jsligo.mdx
- docs/tutorials/smart-contract/smartpy.mdx
- sidebars.js
- src/css/custom.css
- Organize the tutorials sidebar
- Rename some tutorials for consistency
> Divide tutorials sidebar like the tutorials landing page

- docs/unity/reference/TokenContract.md
- docs/unity/scenes.md
These are some links that I can add now that Unity phase 2 is published.
> Unity links

- docs/dApps/samples.md
I propose a few improvements on this page
> Review samples.md

- .github/workflows/tests.yml
I left this `ls` command in by mistake.
> Remove debugging step

- docs/reference/style-guide.md
- docs/tutorials/build-files-archive-with-dal.mdx
- docs/tutorials/build-files-archive-with-dal/get-dal-params.mdx
> Capitalize Data Availability Layer

- docs/tutorials/smart-contract/archetype.md
This TODO was resolved in the Creating a local wallet section.
> Remove stray TODO in Archetype tutorial that has been addressed

- docs/architecture/governance/amendment-history.md
Add info on the Nairobi protocol update, duplicated from opentezos.
> Nairobi protocol

- docs/tutorials/smart-contract/archetype.md
- docs/tutorials/smart-contract/cameligo.mdx
- docs/tutorials/smart-contract/jsligo.mdx
- docs/tutorials/smart-contract/smartpy.mdx
> Smart contract clarifications

- docs/developing/information.md
- sidebars.js
I thought this section could use a good landing page.
Preview: https://docs-staging-git-info-landing-page-trili-tech.vercel.app/developing/information
> Topic about sources of information available to developers and dApps

- docs/tutorials/build-files-archive-with-dal/get-dal-params.md
- docs/tutorials/build-files-archive-with-dal/get-slot-info.md
- docs/tutorials/build-files-archive-with-dal/set-up-environment.md
Updates and clarifications for the DAL file server tutorial:
- Clarify how to get a text editor and how to use docker volumes to make editing in the container easier
- Clarify some commands based on feedback
- How to hide the warning message
> DAL tutorial updates

- docs/tutorials/join-dal-baker/prepare-account.md
In the tutorial you can use your private RPC instead of the public one.
> Use my RPC node

- docs/developing/wallet-setup.md
We need some info on connecting metamask wallets to Tezos. Is this enough info? What other details are there?
- How do I switch https://metamask.tezos.com/ to ghostnet?
- Make sure this works with a Taquito app; I'm getting an error right now with a simple transaction
> Basics of connecting with MetaMask

- docs/smart-contracts/deploying.md
Some info about how to compile the initial storage value for contracts.
> Info about encoding storage values to Micheline for deployment

- docs/architecture/governance.md
Some clarifications to how voting works.
Preview: https://docs-staging-git-voting-trili-tech.vercel.app/architecture/governance
> Simplify the voting process for developers

- docs/tutorials/create-an-nft/nft-web-app.md
This link to the tutorial applications repo is broken.
> Broken link

- docs/tutorials/smart-contract/archetype.md
- docs/tutorials/smart-contract/cameligo.mdx
- docs/tutorials/smart-contract/jsligo.mdx
- docs/tutorials/smart-contract/smartpy.mdx
- Clarify what a wallet is and what tez is
- Include "what is a smart contract" section in Archetype
- Clarify parts of smart contract
- Stress that you can't tamper with the contract after deployment
- Clarify that LIGO is a high-level language
> Tutorial clarifications

- docs/architecture/tokens/FA1.2.md
- docs/architecture/tokens/FA2.md
This MR results from a review of pages on FA1.2 and F12 tokens.
> review pages "FA* tokens"

- docs/architecture/rpc.md
This PR results of reviewing page RPC.
> review page RPC

- docs/architecture/data-availability-layer.md
These changes result from a review of page architecture/DAL. Mostly, some definitions need to be clarified.
> doc: review page DAL

- docs/architecture/baking.md
This PR is a result of reviewing page Baking.
> review page Baking

- docs/overview/index.md
Perform various fixes such as:
- remove mention of Epoxy
> More fixes to Overview

- package-lock.json
- package.json
Faster builds! https://docusaurus.io/blog/releases/3.2
> Upgrade to Docusaurus 3.2.1

- docs/architecture/tokens.md
- docs/architecture/tokens/FA2.md
This implies  that I can put fungible tokens and NFTs in the same contract and we generally don't do that. Simplify some language and show a realistic example of the ledger in a fungible token contract.
> Clarify language around  token types

- docs/developing/sandbox.md
Sandbox and mockup modes are distinct.
> Clarify sandbox and mockup modes

- docs/unity/managing-contracts.md
- docs/unity/scenes.md
> Add a link to the contract on the tutorial scenes page

- docs/tutorials/smartpy-fa2-fungible/adding-metadata.md
Follow-on from https://github.com/trilitech/tezos-developer-docs/pull/385.
> Missed this correction from wyn

- docs/architecture.md
There's a bit more to protocol constants than this, such as the difference between fixed and parametric constants, but this seemed like the right level of detail for this page.
> Info about protocol constants

- docs/architecture/smart-rollups.md
I worked out the math like this:
> Show the math for the length of the refutation period

- .github/workflows/deploy-staging.yml
- docusaurus.config.js
Not sure why, but google has started indexing our staging builds. Adding this to try to block that.
> Add noindex on staging builds

- docusaurus.config.js
> Add noindex on staging builds 

- docs/architecture/tokens.md
I added info on FA2.1 tokens but didn't add it to the tokens overview topic where we talk about standards.
> Mention FA2.1 tokens in the tokens overview topic

- .github/workflows/deploy-production.yml
I have renamed staging to main, so we need to build docs.tezos.com from main.
> Build from new main branch

- docs/tutorials/join-dal-baker/run-dal-node.md
Changes to accompany https://gitlab.com/tezos/tezos/-/merge_requests/14997.
> Mention DAL node connectivity

- src/components/Footer/index.jsx
This link works again: https://discord.gg/tezos
> Use Discord vanity link

- docs/architecture/governance/amendment-history.md
- docs/architecture/governance/improvement-process.md
- docs/developing/testing.md
- docs/smart-contracts/data-types/complex-data-types.md
- docs/smart-contracts/entrypoints.md
- docs/smart-contracts/serialization.md
- docs/tutorials/build-an-nft-marketplace.md
- docs/tutorials/create-an-nft/nft-taquito.md
- docs/tutorials/dapp/part-2.md
- docs/tutorials/mobile/part-2.md
Did a scan for broken links and came up with some links to language sites and the Nomadic labs blog that have changed. Also some Marigold links have gone away.
> Fix broken links

- docs/dApps/taquito.md
- docs/tutorials/build-your-first-app/getting-information.md
Small updates and language clarifications.
> Update docs about Taquito

- docs/overview/tezos-different.md
- Remove info about formal verification
- Update info about delegation and staking from the user perspective
- Add info about layer 2
> Review "What makes Tezos different" page

- docs/architecture/bakers.md
- docs/overview/tezos-different.md
This PR introduces the possibility of staking in the page explaining baking and delegation.
/assign @germanD
> update Baking with the possibility of staking

- docusaurus.config.js
- package-lock.json
- package.json
We must have lost the remark-math plugin somewhere because equations were not showing up. (I think I removed it at some point, sorry.) This looks like a big change to docusaurus.config.js but it's really mostly indentation changes.
Before:
After:
> Fix math equations

- src/components/BuildSection/index.js
Quick review and update of the home page with some updates to the tiles.
> Rework home page

- docs/tutorials/create-an-nft/nft-web-app.md
- docs/tutorials/create-an-nft/nft-web-app/defining-functions.md
- docs/tutorials/create-an-nft/nft-web-app/lets-play.md
- docs/tutorials/create-an-nft/nft-web-app/setting-up-app.md
This tutorial needs some updates for new versions of SmartPy and Taquito.
Update to related dApp and contract in https://github.com/trilitech/tutorial-applications/pull/15.
> Update simple web nft tutorial

- docs/tutorials/join-dal-baker/run-baker.md
To upgrade a baker, run a new daemon for the new protocol side by side and they will switch automatically.
> How to upgrade a baker

- docs/architecture/bakers.md
- docs/overview/index.md
- docusaurus.config.js
- src/components/HomepageFeatures/index.js
- src/components/HomepageFeatures/styles.module.css
Rework the landing page of the website to take into account all the audiences and guide them better to the starting points.
> refactor home page

- docs/smart-contracts/multisig.md
This multisig contract needed to be updated. I've tested compiling and deploying it and I've tested the octez-client built-in multisig commands at the bottom of this topic for good measure.
> Update this multisig contract

- docs/unity/reference/DataProviderConfigSO.md
- docs/unity/reference/TezosConfigSO.md
Hide info about this script element because it's an internal thing.
> This script is an internal thing

- docs/unity/quickstart.md
It's good practice to pin your dependencies.
> How to fix version number

- docs/tutorials/join-dal-baker/run-baker.md
- docs/tutorials/join-dal-baker/run-node.md
This MR will remove the links in this PR:
https://gitlab.com/nomadic-labs-free-resources/opentezos/-/merge_requests/177
> Remove links that will go away

- docs/architecture/bakers.md
Here are a few fixes resulting from a post-review of the last updates to the landing page for bakers.
> small fixes in bakers.md

- docs/using/dapps.md
- sidebars.js
This is so broad that I'm afraid it might not be useful but I think we need a section on dApps to complete the using section.
Preview: https://docs-staging-git-using-dapps-trili-tech.vercel.app/using/dapps
> dApps topic for using section

- docs/tutorials/join-dal-baker.md
> a bit more precise link for HW reqs
