trilitech/tezos-developer-docs

src/pages/baking/baking-explained/index.md

Interestingly changing formulas to inline cause it to wrap onto next line, fixing the issue of it running into the right menu

change formulas to inline

---

src/pages/tutorials/originate-your-first-smart-contract/ligo/index.md
src/pages/tutorials/originate-your-first-smart-contract/smartpy/index.md

These are my suggestions for clarifying the "Originate your first smart contract tutorial." Per discussion with Tezos folks, I'm changing the contract from using a single `main` function to separate functions for each endpoint because the `main` syntax is more complicated and soon to be deprecated.

Clarifying the LIGO contract tutorial

---

src/components/Layout.jsx
src/pages/tutorials/originate-your-first-smart-contract/index.md
src/pages/tutorials/originate-your-first-smart-contract/jsligo/index.md
src/pages/tutorials/originate-your-first-smart-contract/smartpy/index.md

This is a version of the CameLIGO tutorial in jsLIGO. It's essentially the same as the CameLIGO version with minor changes to make it work in jsLIGO and slightly different octez commands to test and deploy the contract.
This PR depends on https://github.com/trilitech/tezos-developer-docs/pull/107.

jsLIGO version of the smart contract tutorial with tutorial overview page

---

docs/developing/information/block-explorers/inspect-contract-tzstats.md
docs/developing/information/indexers.md
sidebars.js

The TzStats API is no longer available publicly; it's now a paid service at https://tzpro.io. Remove info about the TzStats public API. The block explorer site itself is still available.

Remove information about TzStats public API

---

src/css/custom.css

By default, docusaurus uses list numbering like this, with items being numbered like `1.ii.c`:
I think it's easier to read as `1.a.i` as in this example:

Set up styles for nested ordered lists

---

docs/tutorials/smart-contract/cameligo.md
docs/tutorials/smart-contract/jsligo.md

- Update this tutorials to use v1 of LIGO
- Use "tez" instead of "xtz"
- I've tested with ligo 1.1.0 and it works. No need to require v 1.1.0, so it says 1.0.0 or later.

Update smart contract tutorial to use V1 of LIGO

---

src/theme/SearchBar/styles.css

When you type a search query and hover over the results in the search box, the text turns white and disappears:
This update makes the text appear:

Fix text disappearing on hover in the search results box

---

docs/dApps/taquito.md
docs/dApps/wallets.md
docs/tutorials/build-your-first-app/sending-transactions.md
docs/tutorials/build-your-first-app/wallets-tokens.md
docs/tutorials/create-an-nft/nft-taquito.md
docs/tutorials/create-an-nft/nft-web-app/defining-functions.md

Adds a topic on connecting to wallets, which is a critical task for dApp developers.
This PR also updates the use of `requestPermissions`, which no longer accepts parameters per this comment in the Taquito docs:
https://github.com/ecadlabs/taquito/blob/e34e0094539fee4c03c7f6a1120339dc67faed29/docs/wallet_API.md?plain=1#L83
> In previous versions of Beacon, you were able to set the `network` property when doing `requestPermissions()`. This behaviour was removed from Beacon, and you must now set the network when instantiating the wallet.

Clarify info on connecting wallets

---

docs/architecture/rpc.md
docs/dApps/wallets.md
sidebars.js

Still looking into what info is needed about the RPC interface.

Architecture RPC info

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

Old files from previous builds remain in the S3 folder, such as  this page:
https://docs.tezos.com/app-development/taquito/#wallet-setup
This PR cleans the S3 folder before copying the contents of the build output.

Clean output folder before copying contents from build output

---

docusaurus.config.js

Docs are showing up in a subdirectory /docs/, which causes problems like non-working 404 pages.

Serve docs at site root instead of /docs/

---

docs/tutorials.mdx

Using the root like this should make these links work both in dev mode and in prod builds.
Preview: https://docs-staging-git-fix-tutorial-links-trili-tech.vercel.app/tutorials

Fix tutorial links by using the root

---

docs/architecture/tokens.md
docs/architecture/tokens/FA2.md

This PR removes mention of soulbound tokens. You could create a token type that can't be transferred, but TZIP-12 and TZIP-7 require that the tokens actually transfer when you call the transfer entrypoint, therefore they can't support soulbound tokens, so I think the smart thing to do is to remove this mention.

FA2 requires that tokens actually transfer

---

docusaurus.config.js

Docusaurus is html-encoding these quotes and it's breaking them. Removing the quotes until I can work out how to not escape them.

Remove quotes from CSP header

---

docusaurus.config.js

Because of a bug in docusaurus (https://github.com/facebook/docusaurus/issues/9686), when we try to add meta tags with quotes, the quotes always get escaped, which messes up the CSP tag.
This PR adds a dummy tag at build time and uses the `postBuild` hook to update it after the build has finished.

Add CSP meta tag after build

---

docs/developing/information/block-explorers.md

The Octez docs are removing a page with links to community pages. This PR pulls the list of block explorers into the Tezos docs.

Add list of block explorers from octez docs

---

docs/tutorials/smart-contract/cameligo.mdx
docs/tutorials/smart-contract/jsligo.mdx

Had a user get confused trying to dry-run the reset entrypoint, so we need to mention "unit."

Add dry run for reset entrypoint

---

docusaurus.config.js

We might not have to do the post-build replace if we put GTM first in the list of scripts to allow with CSP.

Put GTM first so it gets loaded regardless of the ; problem

---

docs/architecture/tokens/FA2.md
docs/developing/testnets.md
docs/smart-contracts/samples.md
docs/tutorials/create-an-nft/nft-taquito.md

The relationship between the Tezos Foundation and Oxhead Alpha is ending. Remove references to OA.
Is it still OK to link to their example FA2 contracts at https://github.com/oxheadalpha/smart-contracts? I guess we can keep linking there until they remove the repo.

Remove Oxhead Alpha

---

README.md
docusaurus.config.js

Contextual search should be enabled to future-proof the site if we ever offer it in multiple languages or versions. I've verified  that the search works on the staging build based on changes to the crawler. Thanks for the folks at Algolia Docsearch for helping me get the crawler working.

Enable contextual search

---

docs/architecture.mdx
docs/architecture/accounts.md
docs/dApps/taquito.md
docs/overview/glossary.md
docs/smart-contracts/data-types/complex-data-types.md
docs/smart-contracts/data-types/primitive-data-types.md
docs/smart-contracts/deploying.md
docs/smart-contracts/logic/comparing.md
docs/smart-contracts/multisig-usage.md
docs/smart-contracts/special-values.md
docs/tutorials/dapp/part-1.md
docs/tutorials/dapp/part-2.md
docs/tutorials/dapp/part-3.md

It's complicated to talk about "implicit" and "originated" accounts. Simplify by using these terms for accounts:
- User accounts
- Smart contract accounts
- Smart Rollup accounts

Account types

---

docs/smart-contracts/events.md

Example of emitting an events in JsLIGO. Re-upload of https://github.com/trilitech/tezos-developer-docs/pull/259.

Ligo events example

---

docs/tutorials/build-files-archive-with-dal.mdx

I think I understand what this note is saying better now.

Clarify this note about methods

---

docs/reference/style-guide.md
sidebars.js

Style guide for Tezos docs based on things I've observed. Very open to suggestions here.
This guide does not take a stance on US English vs. British English. en_US is more popular but en_GB would be fine because TriliTech is a British-based company.
Preview: https://docs-staging-git-style-guide-trili-tech.vercel.app/reference/style-guide

Style guide

---

docs/dApps/quickstart.md
docs/smart-contracts/quickstart.md
sidebars.js

Based on discussion in https://github.com/trilitech/tezos-developer-docs/pull/219, we're not going to provide dApp or smart contract quickstarts because it would just be a rehash of the beginner tutorials.

Remove quickstart TODOs and stubs

---

sidebars.js

The recently merged Support page is misplaced in the left menu, as it breaks the flow.

Adjust support page

---

docs/tutorials/join-dal-baker/run-baker.md

With the merging of DAL and consensus attestations in https://gitlab.com/tezos/tezos/-/merge_requests/11462, the log messages displayed by the baker have changed a bit. This PR updates the DAL baking tutorial accordingly.

DAL+baker tuto: update the expected DAL attestation log message

---

docs/architecture/rpc.md

This page mentions the shell RPC endpoints but not the protocol RPC endpoints. This PR adds a link to the protocol RPC info on tezos.gitlab.io.

Mention RPC endpoints for protocol

---

docs/smart-contracts/languages/ligo.md

This is the preferred way to do entrypoints and it's easier to read. I used this contract: https://docs.tezos.com/tutorials/smart-contract/jsligo#creating-the-contract

Update LIGO example to use separate entrypoints

---

docs/tutorials/join-dal-baker/get-octez.md
docs/tutorials/join-dal-baker/prepare-account.md
docs/tutorials/join-dal-baker/run-dal-node.md

Working on some clarifications from feedback.

DAL baker tutorial updates

---

docs/architecture/tokens/FA1.2.md
docs/architecture/tokens/FA2.md

I was wrong to talk about the recommended views of FA2 contracts; they are off-chain views as described here:
https://gitlab.com/tezos/tzip/-/blob/master/proposals/tzip-12/tzip-12.md#off-chain-views
This PR removes references to the views of FA2 contracts.

Correct token off chain views

---

docs/tutorials/join-dal-baker/get-octez.md
docs/tutorials/join-dal-baker/prepare-account.md

In the DAL baker tutorial, we initialize the client in step 1 but do not use it. Then in step 3 we set its configuration. It's simpler to do this config once, so this PR removes that client initialization in step 1.

No need to configure the client so early

---

docs/architecture/smart-rollups.md

"Operators" are nodes running in operator mode, not people. Remove the mention of "operator" as the person who originates the rollup.

SCORU originator is not an operator

---

docs/architecture/tokens.md

The page `tokens.md` presents various issues, such as:
* The list of tokens in the introductions mixes different categories in a flat way: native/programmed tokens; fungible/non-fungible; stablecoins; wrapped. This list can be much better structured, exhibiting the various categories and showing which tokens belong to which category.
* In particular, the phrase "Tokens are not stored directly in accounts" only concerns non-native tokens.
* "Fungible tokens, which are interchangeable and accounts can own any amount of" is false when considering tokens in limited number.
* "One exception is tickets, which are directly stored and managed by smart contracts" is ambiguous, as the previous phrase also talks about tokens managed by a smart contract.
The MR proposes fixes for that, and for other …

review page Tokens

---

docs/dApps.md
docs/overview/common-applications.md
docs/unity.md
docs/unity/connecting-accounts.md
docs/unity/prefabs.md
docs/unity/quickstart.md
docs/unity/reference.md
sidebars.js

Renamed the name of the SDK as "Tezos Unity SDK" for the planned rebranding.
Replaces https://github.com/trilitech/tezos-developer-docs/pull/363.

Rename "Tezos SDK for Unity" to "Tezos Unity SDK"

---

docs/tutorials/build-files-archive-with-dal/publishing-on-the-dal.md

The path of the RPC used to publish a slot on the DAL has changed (`/slot` has become `/slots`). This PR updates the tutorial accordingly.

Update a RPC path in DAL rollup tutorial

---

docs/smart-contracts/serialization.md

Info about packing and unpacking and some gotchas about the formatting.
Preview: https://docs-staging-git-packing-details-trili-tech.vercel.app/smart-contracts/serialization#formatting
- Should the Octez docs mention this formatting and provide more detail, such as the possible values for prefixes?
- Is this info about the octez-codec useful here? I added just the command to print out all the formatting info. https://tezos.stackexchange.com/a/4000/10849
Source: https://tezos.stackexchange.com/questions/5879/conversion-of-address-to-bytes/5895#5895

Details about packing and unpacking

---

src/components/HomepageFeatures/index.js

Fix the link to a page that was moved in #361.
What can be more frustrating for a new developer than clicking into `start developing` just to see nothing but `page not found`? :)

Fix card `Development environments` in the landing page

---

docs/smart-contracts/data-types/complex-data-types.md
docs/smart-contracts/data-types/primitive-data-types.md

Got some questions in discord about unit so I thought we should mention it here.

Info about the unit type

---

docs/architecture/tokens/FA1.2.md
docs/architecture/tokens/FA2.1.md
sidebars.js

Docs for FA2.1 in the same style as FA2.
Preview: https://docs-staging-git-fa-21-trili-tech.vercel.app/architecture/tokens/FA2.1

Docs for FA2.1 standard

---

src/scripts/process_downloaded_glossary.js

The headings for the imported glossary show the hash mark all the time, but the rest of the site shows them only on hover. 
In this screencap, the hash is shown even when the mouse is not over the heading:
This PR changes the header links in the imported glossary from this:
```
<a class="headerlink" href="#tezos" title="Link to this heading">#</a>
```
To this, which matches other links on the site:
```
<a class="hash-link" href="#tezos" title="Direct link to Tezos" aria-label="Direct link to Tezos"></a>
```

Fix hash for glossary headings

---

src/components/TutorialCard/index.js
src/components/TutorialCard/styles.module.css

The tutorial tile component is clickable only on the Start tutorial link. This makes it so the whole tile is clickable.

Make the whole tutorial tile a link

---

docs/tutorials/smart-rollup/deploy.md
docs/tutorials/smart-rollup/optimize.md
docs/tutorials/smart-rollup/run.md
docs/tutorials/smart-rollup/set-up.md

Tutorial needs some updates, primarily that for the binary you can use `octez-smart-rollup-node` without the `alpha`.
Related issue: if you wait too long between origination and starting the Smart Rollup node, it can't get enough info from the rolling L1 node. This fix changes the sandbox for this tutorial to use an archive node: https://gitlab.com/trili/hello-world-kernel/-/merge_requests/4

Update Smart Rollup tutorial

---

docs/architecture/baking.md

This MR proposes to add one reference from the Baking page to the one in the Octez doc, alongside the reference to OpenTezos.

improve refs for baking

---

docs/architecture/data-availability-layer.md
docs/tutorials.mdx
docs/tutorials/join-dal-baker.md
docs/tutorials/join-dal-baker/conclusion.md
docs/tutorials/join-dal-baker/run-dal-node.md
docs/tutorials/join-dal-baker/run-node.md
docs/tutorials/join-dal-baker/verify-rights.md
sidebars.js

We're going to keep this DAL baker tutorial along with the topic on [Running a DAL attester node](https://tezos.gitlab.io/shell/dal_run.html) even though they overlap because we want to get people running DAL nodes and some might like a complete guide for doing it from scratch.
Takes over on #455.
Preview: 
https://docs-staging-git-rework-dal-baker-tutorial-trili-tech.vercel.app/tutorials/join-dal-baker
- Refer to this as a guide because it's not really a tutorial
- Focus on Ghostnet but provide info for other networks
- Link to the Octez docs for people who are more familiar with the process
- Move it to the section for "Intermediate" tutorials, rather than "Advanced"
- Add installation details
- Clarify introduction to send current bakers to Octez docs and to explain that this tutorial …

Rework DAL baker tutorial

---

docs/developing.md
docs/developing/octez-client/accounts.md
docs/developing/sandbox.md
docs/developing/testing.md
docs/developing/testnets.md
docs/tutorials/join-dal-baker.md
docs/unity/quickstart.md

- Move Tezbox above Flextesa because it's supported
- Rename "sandboxes and testnets" topic because it's just about testnets
- Update Tezbox instructions for Paris

Update info about sandboxes

---

docs/tutorials/build-your-first-app/setting-up-app.md

This tutorial needs a small update for Svelte 5:
https://svelte.dev/docs/svelte/v5-migration-guide#Components-are-no-longer-classes
Updates to the application itself in: https://github.com/trilitech/tutorial-applications/pull/13

Update app for Svelte 5

---

.github/workflows/deploy-production.yml
.gitignore
package-lock.json
package.json
src/scripts/concatenate.js
src/scripts/concatenate.mjs

This script concatenates all MD files and strips the markdown code into a single text file so you can feed it to an LLM. Run it by running `npm run concat`. It outputs to `allPageSourceFiles.txt` and if I've done it correctly, that file will be at https://docs.tezos.com/allPageSourceFiles.txt.

Script to concatenate MD files

---

docs/tutorials/join-dal-baker/run-dal-node.md

In some cases you can improve networking performance by exposing ports and setting up port forwarding but based on discussion this is enough to get most people started.

Clarify DAL node networking, just covering the basics

---

src/scripts/concatenate.mjs

I noticed some more escapes in the output file that need to be cleaned up. For example, the output markdown escapes `-` at the first character of a line like this:
```
Account address | Balance
\--- | ---
tz1QCVQinE8iVj1H2fckqx6oiM85CNJSK9Sx | 5
tz1hQKqRPHmxET8du3fNACGyCG8kZRsXm2zD | 12
tz1Z2iXBaFTd1PKhEUxCpXj7LzY7W7nRouqf | 3
```
This change filters these escapes out and makes a not about how we may be able to do this more efficiently in the future.

Clean up escapes

---

docs/tutorials/create-an-nft/nft-tznft.md

This tool is in maintenance mode and is kind of outdated, so we may consider removing it, but for now here is a small update. 
Related issue is that it uses an outdated RPC node:
https://github.com/oxheadalpha/nft-tutorial/pull/94

Small updates to the tznft tutorial

---

.github/CODEOWNERS

The Dev Success team no longer exists. Update the team that is asked to review PRs in this repo.
New team is https://github.com/orgs/trilitech/teams/tur-docs

Update codeowners for current team working on docs

---

docs/tutorials/smartpy-fa2-fungible/basic-fa2-token.md

SmartPy 0.20.0 handles imported modules slightly differently.
Related updates to completed tutorial files here:
https://github.com/trilitech/tutorial-applications/pull/14

Update smartpy nft tutorial

---

docs/tutorials/create-an-nft/nft-taquito.md
docs/tutorials/create-an-nft/nft-tznft.md
docs/tutorials/create-an-nft/nft-web-app.md

I created this as a potential solution to https://github.com/trilitech/tezos-developer-docs/issues/473.
Provides disambiguation for the 3 NFT-related tutorials. Not sure if it's better to do this or to reduce the number of tutorials. Very open to opinions. I did not mention the tznft tutorial because I'm considering removing it because tznft is no longer maintained and it's a very niche tool.
Fixes https://github.com/trilitech/tezos-developer-docs/issues/473.

Disambiguate NFT tutorials

---

docs/overview/index.md
docs/overview/resources.md
docs/reference/textfiles.md
sidebars.js

Preview: https://docs-staging-git-links-to-txt-files-trili-tech.vercel.app/reference/textfiles

Add a page that refers to the text files

---

docs/developing/octez-client/transactions.md
docs/tutorials/join-dal-baker/run-dal-node.md

Clarify a few places where we use variables without explaining what they are. We can assume that $HOME and $PATH are defined, but if I use $MY_ACCOUNT that should have been explicitly defined.

Clarify variables

---

docusaurus.config.js
package-lock.json
package.json

Enable the feedback widget. We've been using it on Etherlink's docs and it works well.
https://github.com/etherlinkcom/docs/pull/98

Enable pushfeedback widget

---

docs/tutorials/join-dal-baker/prepare-account.md
docs/tutorials/join-dal-baker/run-baker.md
docs/tutorials/join-dal-baker/run-dal-node.md
docs/tutorials/join-dal-baker/run-node.md
docs/tutorials/join-dal-baker/verify-rights.md

I followed the tutorial <https://docs.tezos.com/tutorials/join-dal-baker> and here is what I found.

Review the tutorial join-dal-as-baker

---

docs/architecture/nodes.md
docs/tutorials/join-dal-baker.md
docs/tutorials/join-dal-baker/run-baker.md
docs/tutorials/join-dal-baker/run-dal-node.md
docs/tutorials/join-dal-baker/run-node.md
sidebars.js

This tutorial is going to be the primary place we point people to for instructions about running a node:
- Recast it from a DAL node tutorial to a node tutorial that includes a DAL node.
- Make consistent the systemd service files
- Use the `tezos` user to run the services

Recast this as a node/baker/DAL tutorial

---

test/images.test.mjs

The image test is failing when combined with the checkChangedFiles action. The `getAllUsedImages` function needs to get all images in all MD files, not just the MD files that were changed in the PR.
To test, check out the main branch and check for missing images in only one file with this command. It returns errors about unused images:
```bash
npm run test -- --filesToCheck=docs/architecture.md
```
Then load this branch, run  the same command, and see that the test passes.

Always load all MD files to check for images

---

docs/using.md
sidebars.js

Just a landing page for the using section. Not sure what else to add at this level of detail.
Preview: https://docs-staging-git-using-overview-trili-tech.vercel.app/using

Using section overview topic

---

docs/developing/octez-client.md
docs/tutorials/join-dal-baker.md

The link https://tezos.gitlab.io/releases/latest.html should always link to information for the current release of Octez.

Link to system requirements for Octez

---

docs/reference/textfiles.md

Per the warning at the bottom of [this page](https://docusaurus.io/docs/markdown-features/links), you can't link from a file that Docusaurus processes to a file that it does not process with a relative or root-relative link. For this reason, when you go to https://docs.tezos.com/textfiles and click on a file name, the site will show a 404 even though the path is correct. Setting the links to absolute https links fixes this.

Must use absolute links to files not processed by Docusaurus

---

docs/architecture/bakers.md
docs/architecture/governance.md
docs/architecture/governance/amendment-history.md
docs/architecture/smart-rollups.md
docs/tutorials/join-dal-baker/run-baker.md
docs/tutorials/join-dal-baker/run-node.md
docs/using/staking.md

- Block time is 8s on Mainnet and 4s on Ghostnet but length of cycle stays the same
- Add main features for Quebec
- Change names of baker and accuser binary
- Delegated funds now count 1/3 toward a baker's baking power (voting power still at 100%)
- How much tez do I receive in return for staking tez?
Do not merge until 20 January.

Changes in Quebec

---

docs/tutorials.mdx

Two intermediate tutorials have no tiles on https://docs.tezos.com/tutorials. This PR adds them.
Preview: https://docs-staging-git-tutorial-tiles-trili-tech.vercel.app/tutorials#intermediate

Add tiles for these two tutorials

---

docs/tutorials/join-dal-baker/verify-rights.md

How to revoke a consensus key and use it to drain, based on info in https://opentezos.com/node-baking/baking/consensus-key/#register-a-consensus-key.

How to revoke a consensus key and drain with it

---

docs/architecture/bakers.md
docs/tutorials/join-dal-baker/run-baker.md
docs/tutorials/join-dal-baker/run-node.md

- Use protocol-specific file names and service names for systemd services because during upgrade you'll have two bakers and two accusers running
- Provide example file names and example commands for using the service files with systemd

Provide example systemd file names and commands

---

docs/tutorials/join-dal-baker/prepare-account.md

Fix issue #527 by reordering the operations for setting up a baker account, in the baking tutorial page <https://docs.tezos.com/tutorials/join-dal-baker/prepare-account>.

fix order of baker account setup (issue #527)

---

docs/architecture/governance/improvement-process.md
docs/architecture/tokens.md
docs/developing/testing.md
docs/smart-contracts/data-types/complex-data-types.md
docs/smart-contracts/data-types/crypto-data-types.md
docs/smart-contracts/data-types/primitive-data-types.md
docs/smart-contracts/delegation.md
docs/smart-contracts/entrypoints.md
docs/smart-contracts/events.md
docs/smart-contracts/languages/smartpy.md
docs/smart-contracts/logic/comparing.md
docs/smart-contracts/logic/errors.md
docs/smart-contracts/logic/operations.md
docs/smart-contracts/samples.md
docs/smart-contracts/serialization.md
docs/smart-contracts/special-values.md
docs/smart-contracts/storage.md
docs/smart-contracts/views.md
docs/tutorials/smartpy-fa2-fungible/basic-fa2-token.md

The reworked SmartPy docs have some redirects in place but it would be good to update our links to them.
See also https://gitlab.com/nomadic-labs-free-resources/opentezos/-/merge_requests/174.

Update SmartPy links

---

docs/unity/calling-contracts.md

Unity can send transactions to Etherlink but it cannot switch your wallet to Etherlink.
Is this enough, or should we mention this limitation here, too?
https://docs.tezos.com/unity/connecting-accounts#connecting-to-walletconnect-wallets

Document limitation of switching networks

---

docs/architecture/bakers.md
docs/tutorials/join-dal-baker.md
docs/tutorials/join-dal-baker/run-baker.md
docs/using/staking.md

Before we remove baking-related pages from opentezos and direct baking and staking info here, make sure that docs.tezos.com has all of the info from that page.
This PR has a few small updates from these pages, including a few things to check before selecting a baker and the info that some wallets and exchanges have built-in staking functions.
It takes info from these pages:
- https://opentezos.com/node-baking/baking/bakers_list/
- https://opentezos.com/node-baking/baking/delegating/
- https://opentezos.com/node-baking/baking/cli-baker/

Update staking page based on OpenTezos page on delegating

---

sidebars.js

Left this page out of the TOC by mistake.
Here's the page, it just needs to be added to the sidebar: https://docs.tezos.com/unity/upgrading

Restore upgrading Unity page

---

docs/tutorials/bake-with-ledger/run-baker.md

Some feedback on our `Baking with Ledger` tutorial has been received.
This PR deals with these comments.
The [command to runs](https://docs.tezos.com/tutorials/join-dal-baker/prepare-account) for it as been included.

[baking-with-ledger] handles feedback

---

src/scripts/check_dependencies.mjs

The current dependency script alerts on any version difference up to the fixpack level. This change allows you to pass `--major` to show only places where dependencies are out of date by the major version or `--minor` for minor version.
For example, `npm run check-dependencies -- --major octez` prints this:
```
docs/tutorials/smart-rollup.md
Outdated: octez 19 < 21.2
Reviewed 154 files.
```
But `npm run check-dependencies -- --minor octez` prints this:
```
docs/developing/octez-client/accounts.md
Outdated: octez 21.1 < 21.2
docs/developing/octez-client/installing.md
Outdated: octez 21.1 < 21.2
docs/developing/octez-client/transactions.md
Outdated: octez 21.1 < 21.2
docs/tutorials/smart-rollup.md
Outdated: octez 19 < 21.2
Reviewed 154 files.
```

Allow filtering by version level

---

docs/architecture/smart-rollups.md

Per feedback, provide some more info about recovering bonds.

More info about recovering bond

---

README.md
src/scripts/check_dependencies.mjs

Eventually we'll want to filter the dependency check by file, so this PR reworks the script into accepting three params:
- You can check specific tools by passing them to the script, as in `npm run check-dependencies -- --dependencies=smartpy,taquito`.
- By default, the script checks for differences down to the fixpack level, but you can pass `--major` or `--minor` to check for differences at those levels.
- By default, it checks all files, but you can pass individual files to check in a comma-separated list, as in `npm run check-dependencies -- --filesToCheck=docs/developing/octez-client/accounts.md,docs/tutorials/build-your-first-app.md`.
The script has error-checking to catch unknown parameters and dependencies. If you pass an incorrect file path, you'll get the usual Node ENOENT error …

Filter dependencies by file

---

README.md
src/scripts/check_dependencies.mjs

For dependency checks we should be able to pass individual paths or files. This PR allows you to pass any combination, as in these examples:
```
npm run check-dependencies -- --major -d=smartpy,taquito docs/developing/octez-client/accounts.md docs/tutorials
npm run check-dependencies -- --major -d=smartpy,taquito docs/*
```
The shell expands the `*` in the anonymous arguments before it gets to the script but I think I've got it working despite that.

Allow paths or specific files

---

docs/tutorials/build-files-archive-with-dal/get-slot-info.md
docs/tutorials/build-files-archive-with-dal/publishing-on-the-dal.md

- `--legacy` is no longer required for the DAL trusted setup but I left it in there for older versions of Octez
- Add troubleshooting step to verify that the DAL node is configured
- Add how to get DAL data via RPC

DAL updates

---

docs/tutorials/smart-rollup.md

Related to https://github.com/etherlinkcom/docs/pull/246, seems some people need this step.

People are reporting this prereq

---

docs/dApps/sending-transactions.md
docs/dApps/taquito.md

Taquito uses `methodsObject` instead of `methods` now.

Update Taquito examples

---

docs/tutorials/join-dal-baker/run-baker.md

Need to backup nonce files if you move the baker to another machine.

Backup and restore instructions for nonce files

---

docs/tutorials/bake-with-ledger/setup-ledger.md

Some users have experienced problems while baking with their Ledger. It would appear that this is because the Ledger's battery saver option was activated and the Ledger shut itself down. This PR adds a section advocating the deactivation of this option.

[baking-with-ledger] recommend to disable the `Battery saver`

---

docs/architecture/governance/improvement-process.md

Just a regular review to clean up some things and add relevant links.
Preview: https://docs-staging-git-review-tzip-trili-tech.vercel.app/architecture/governance/improvement-process

Review TZIP topic
